export const tFileList = [
    {
        "content":"",
        "createTime":null,
        "default_field":"1",
        "describes":"备注",
        "eid":0,
        "enterpriseDictionaries":null,
        "icon":"iconfont icon-icon-test1",
        "id":1,
        "lableList":null,
        "map":null,
        "name":"备注",
        "taskAndField":null,
        "taskAndFieldList":[
                {
                "content":"待添加<p>这是备注文字</p>",//【备注内容】
                "createTime":null,
                "id":295,
                "tid":630,
                "typeId":1,
                "updateTime":null
            }
        ],
        "type":"7",
        "updateTime":null
    },
    {
        "content":"",
        "createTime":null,
        "default_field":"1",
        "describes":"",
        "eid":0,
        "enterpriseDictionaries":null,
        "icon":"iconfont icon-liebiaoxunhuan",
        "id":2,
        "lableList":null,
        "map":null,
        "name":"优先级",
        "taskAndField":null,
        "taskAndFieldList":[

        ],
        "type":"0",
        "updateTime":null
    },
    {
        "content":"",
        "createTime":null,
        "default_field":"1",
        "describes":"",
        "eid":0,
        "enterpriseDictionaries":null,
        "icon":"iconfont icon-biaoqian",
        "id":3,
        "lableList":[
            {
                "bq_color":"#69B6FD",//【标签颜色】
                "createPeopleId":0,
                "createTime":null,
                "del":0,
                "fid":"3",
                "id":61,
                "name":"我1",//【标签名称】
                "pid":291,
                "state":0,
                "updateTime":null
            },
            {
                "bq_color":"#69B6FD",//【标签颜色】
                "createPeopleId":0,
                "createTime":null,
                "del":0,
                "fid":"3",
                "id":62,
                "name":"我1",//【标签名称】
                "pid":291,
                "state":0,
                "updateTime":null
            },
            {
                "bq_color":"#69B6FD",//【标签颜色】
                "createPeopleId":0,
                "createTime":null,
                "del":0,
                "fid":"3",
                "id":63,
                "name":"我1",//【标签名称】
                "pid":291,
                "state":0,
                "updateTime":null
            },
            {
                "bq_color":"#69B6FD",//【标签颜色】
                "createPeopleId":0,
                "createTime":null,
                "del":0,
                "fid":"3",
                "id":64,
                "name":"我1",//【标签名称】
                "pid":291,
                "state":0,
                "updateTime":null
            },
            {
                "bq_color":"#69B6FD",//【标签颜色】
                "createPeopleId":0,
                "createTime":null,
                "del":0,
                "fid":"3",
                "id":65,
                "name":"我1",//【标签名称】
                "pid":291,
                "state":0,
                "updateTime":null
            }
        ],
        "map":null,
        "name":"标签",
        "taskAndField":null,
        "taskAndFieldList":null,
        "type":"6",
        "updateTime":null
    },
    {
        "content":"",
        "createTime":null,
        "default_field":"1",
        "describes":"任务目标",
        "eid":0,
        "enterpriseDictionaries":null,
        "icon":"iconfont icon-wenjian",
        "id":4,
        "lableList":null,
        "map":null,
        "name":"任务目标",
        "taskAndField":null,
        "taskAndFieldList":[
            {
                "content":"这是任务目标文字",//【任务目标内容】
                "createTime":null,
                "id":294,
                "tid":630,
                "typeId":4,
                "updateTime":null
            }
        ],
        "type":"7",
        "updateTime":null
    },
    {
        "content":"",
        "createTime":null,
        "default_field":"1",
        "describes":"工时",
        "eid":0,
        "enterpriseDictionaries":null,
        "icon":"iconfont icon-icon-test2",
        "id":5,
        "lableList":null,
        "map":{
            "planTime":"0",
            "countTime":"0"
        },
        "name":"工时",
        "taskAndField":null,
        "taskAndFieldList":null,
        "type":"0",
        "updateTime":null
    },
    {
        "content":"",
        "createTime":null,
        "default_field":"1",
        "describes":"进度",
        "eid":0,
        "enterpriseDictionaries":null,
        "icon":"iconfont icon-flag",
        "id":6,
        "lableList":null,
        "map":null,
        "name":"进度",
        "taskAndField":null,
        "taskAndFieldList":[

        ],
        "type":"0",
        "updateTime":null
    }
]